apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-frontend-deploy
spec:
  selector:
    matchLabels:
      app: ms-frontend
  template:
    metadata:
      labels:
        app: ms-frontend
    spec:
      containers:
      - name: ms-frontend
        image: tiztan21/ms-frontend:01
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        env:
          - name: PRODUCTS
            value: products-service
          - name: SHOPPING
            value: shopping-service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: ms-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: NodePort