apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-products-deploy
spec:
  selector:
    matchLabels:
      app: ms-products
  template:
    metadata:
      labels:
        app: ms-products
    spec:
      containers:
      - name: ms-products
        image: tiztan21/ms-products:01
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: products-service
spec:
  selector:
    app: ms-products
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP