apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-shopping-deploy
spec:
  selector:
    matchLabels:
      app: ms-shopping
  template:
    metadata:
      labels:
        app: ms-shopping
    spec:
      containers:
      - name: ms-shopping
        image: tiztan21/ms-shopping-cart:01
        resources:
          limits:
            memory: "50Mi"
            cpu: "100m"
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  selector:
    app: ms-shopping
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP